### ISSUE TITLE
Audio: audio output from jack is not working

### ISSUE THREAD

**Issue by wisniew** [sailfishos-oneplus5/important#3]
When headphones are plugged in music still play on speaker rather than headphones.

**Comment by JamiKettunen** [comment]
We probably need something similar [like this](https://github.com/mlehtima/droid-config-fp2-sibon/commit/eba60de9dcafc778c890f3d7ad80dd98c4f7d37c). I only tried a `sparse/etc/ohm/plugins.d/accessories.ini` file alone (which just broke everything), so this `ohmd` hack may be necessary.
Gonna do some more research later :)

**Comment by JamiKettunen** [comment]
This seems to be resolved back on 15.1 as media & system audio both play from headphones, as well as microphone works on a wired pair of headbuds (didn't test calling but I'd assume it works fine).
I'll have to get back on this when I get an actually working base on 16.0/17.x; closing for now though.
