### ISSUE TITLE
 /boot/boot-initramfs.gz;5f839c81: cpio: open failed - File exists

### ISSUE THREAD

**Issue by taskforpid** [sailfishos-oneplus5/important#6]
build_all_packages --version

The following NEW package is going to be installed:
  droid-hal-cheeseburger-kernel

1 new package to install.
Overall download size: 0 B. Already cached: 13.7 MiB. After the operation, additional 16.6 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Installation of droid-hal-cheeseburger-kernel-0.0.6-202010112336.armv7hl failed:
Error: Subprocess failed. Error: RPM failed: error: unpacking of archive failed on file /boot/boot-initramfs.gz;5f839c81: cpio: open failed - File exists
error: droid-hal-cheeseburger-kernel-0.0.6-202010112336.armv7hl: install failed

Abort, retry, ignore? [a/r/i] (a): a
Problem occurred during or after installation or removal of packages:
Installation aborted by user
Setting version: 1.0.3+master.20200920202750.4a0263b
error: Failed build dependencies:
	droid-hal-kernel is needed by droid-hal-version-cheeseburger-0.0.1-202010120000.armv7hl
Building target platforms: armv7hl-meego-linux
Building for target armv7hl-meego-linux

And this command is not helped:
sb2 -t $VENDOR-$DEVICE-$PORT_ARCH -m sdk-install -R zypper in ...

**Comment by JamiKettunen** [comment]
Closing since the same question was answered in https://github.com/sailfish-oneplus6/sf-enchilada/issues/13#issuecomment-707025606 as well.
